<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tourze Lite Gutenverse Search Hero', 'tourze-lite' ),
	'categories' => array( 'tourze-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290","Tablet":""},"gap":"no","elementId":"guten-HIlJi7","background":{"type":"default","image":{"Desktop":{"id":222,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/water-architecture-bridge-chateau-palace-river-861263-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"fetchPriorityHigh":true},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-background-secondary"}},"opacity":"0.8","padding":{"Desktop":{"unit":"px","dimension":{"top":"280","bottom":"140"}},"Mobile":{"unit":"px","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="HIlJi7"><section class="wp-block-gutenverse-section guten-element guten-section guten-HIlJi7 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-HujPbv","horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HujPbv"><div class="guten-column-wrapper" data-id="HujPbv"><!-- wp:gutenverse/search-result-title {"elementId":"guten-eT7UG4","alignment":{"Desktop":"center"},"typography":{"type":"variable","id":"gv-font-heading-inner-page","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"72"},"Tablet":{"unit":"px","point":"68"},"Mobile":{"unit":"px","point":"48"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"color":{"type":"variable","id":"gv-color-secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20"}}}} -->
<div class="guten-element guten-search-result-title guten-eT7UG4"></div>
<!-- /wp:gutenverse/search-result-title -->

<!-- wp:gutenverse/search {"elementId":"guten-gCS155","placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputPlaceholder":"Search here...","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"20","bottom":"12","left":"20"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"15"}}},"inputWidth":{"Desktop":{"point":"400","unit":"px"}},"inputTypography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}}},"inputBorderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}},"inputBorderFocus":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent-hover"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"gv-color-white"}},"alignContent":{"Desktop":"center"}} -->
<div class="guten-element guten-gCS155 guten-search"><form class="gutenverse-search-form"><div class="search-input-container-outer"><div class="search-input-container"><input type="text" placeholder="Search here..." name="s" class="gutenverse-search gutenverse-search-input"/><div class="close-icon"><i class="gtn gtn-x-line"></i></div></div></div><div class="guten-search-button-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-ICJqIg","role":"submit","content":"","buttonSize":"xs","buttonWidth":{"Desktop":""},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"","right":"17","bottom":"","left":"17"}}},"buttonBackground":{"color":{"type":"variable","id":"gv-color-accent"},"type":"default"},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"showIcon":true,"icon":"gtn gtn-search11-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0zMC45MzggMjkuNTMxbC03LjM3NS03LjM0NHExLjM3NS0xLjY4OCAyLjE1Ni0zLjc4MXQwLjc4MS00LjQwNnEwLTIuNjg4LTEtNS4wMzEtMS4wMzEtMi4zNDQtMi43ODEtNC4wOTR0LTQuMDk0LTIuNzgxcS0yLjM0NC0xLTUuMDMxLTF0LTUuMDMxIDFxLTIuMzQ0IDEuMDMxLTQuMDk0IDIuNzgxdC0yLjc4MSA0LjA5NHEtMSAyLjM0NC0xIDUuMDMxIDAgMi42NTYgMSA1LjAzMSAxLjAzMSAyLjM0NCAyLjc4MSA0LjA5NHQ0LjA5NCAyLjc1cTIuMzQ0IDEuMDMxIDUuMDMxIDEuMDMxIDIuMzQ0IDAgNC40MjItMC43ODF0My43NjYtMi4xNTZsNy4zNDQgNy4zNzVxMC4zNzUgMC4zNzUgMC45MDYgMC4zNzV0MC45MDYtMC4zNzUgMC4zNzUtMC45MDYtMC4zNzUtMC45MDZ2MHpNMTMuNTk0IDI0LjM0NHEtMi4xMjUgMC00LjAzMS0wLjgxMy0xLjg3NS0wLjgxMy0zLjI4MS0yLjIxOXQtMi4yMTktMy4zMTNxLTAuODEzLTEuODc1LTAuODEzLTQgMC0yLjE1NiAwLjgxMy00LjAzMXQyLjIxOS0zLjI4MSAzLjI4MS0yLjIxOXExLjkwNi0wLjgxMyA0LjAzMS0wLjgxM3Q0LjAzMSAwLjgxM3ExLjg3NSAwLjgxMyAzLjI4MSAyLjIxOXQyLjIxOSAzLjI4MSAwLjgxMyA0LjAzMXEwIDIuMTI1LTAuODEzIDQtMC44MTMgMS45MDYtMi4yMTkgMy4zMTN0LTMuMjgxIDIuMjE5cS0xLjkwNiAwLjgxMy00LjAzMSAwLjgxM3oiPjwvcGF0aD4KPC9zdmc+Cg==","iconSpacing":{"Desktop":"0"},"iconSize":{"Desktop":{"unit":"px","point":"16"}},"color":{"type":"variable","id":"gv-color-white"},"iconColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"500"},"positioningType":{"Desktop":"inline"},"ariaLabel":"Submit search"} -->
<div class="guten-element guten-button-wrapper guten-ICJqIg"><button class="guten-button guten-button-xs" aria-label="Submit search" type="submit"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M30.938 29.531l-7.375-7.344q1.375-1.688 2.156-3.781t0.781-4.406q0-2.688-1-5.031-1.031-2.344-2.781-4.094t-4.094-2.781q-2.344-1-5.031-1t-5.031 1q-2.344 1.031-4.094 2.781t-2.781 4.094q-1 2.344-1 5.031 0 2.656 1 5.031 1.031 2.344 2.781 4.094t4.094 2.75q2.344 1.031 5.031 1.031 2.344 0 4.422-0.781t3.766-2.156l7.344 7.375q0.375 0.375 0.906 0.375t0.906-0.375 0.375-0.906-0.375-0.906v0zM13.594 24.344q-2.125 0-4.031-0.813-1.875-0.813-3.281-2.219t-2.219-3.313q-0.813-1.875-0.813-4 0-2.156 0.813-4.031t2.219-3.281 3.281-2.219q1.906-0.813 4.031-0.813t4.031 0.813q1.875 0.813 3.281 2.219t2.219 3.281 0.813 4.031q0 2.125-0.813 4-0.813 1.906-2.219 3.313t-3.281 2.219q-1.906 0.813-4.031 0.813z"></path>
</svg>
</div><span></span></button></div>
<!-- /wp:gutenverse/button --></div></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
