<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tourze Lite Gutenverse Home About', 'tourze-lite' ),
	'categories' => array( 'tourze-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-n7PHQ2","overflow":"hidden","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"right":"15","left":"15","top":"80","bottom":"100"}}},"zIndex":{"Desktop":1}} -->
<div class="section-wrapper" data-id="n7PHQ2"><section class="wp-block-gutenverse-section guten-element guten-section guten-n7PHQ2 layout-boxed align-stretch overflow-hidden"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":48,"Tablet":100},"elementId":"guten-GtZi6c","horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GtZi6c"><div class="guten-column-wrapper" data-id="GtZi6c"><!-- wp:gutenverse/spacer {"elementId":"guten-7d5AQf","space":{"Desktop":{"unit":"px","point":"580"},"Mobile":{"unit":"px","point":"392"}}} -->
<div class="guten-element guten-spacer guten-7d5AQf"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/image {"elementId":"guten-TeQj7l","imgSrc":{"media":{"imageId":779,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/landscape-nature-wilderness-walking-mountain-sky-tourze-lite.webp","orientation":"landscape"},"medium":{"height":235,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/landscape-nature-wilderness-walking-mountain-sky-tourze-lite.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/landscape-nature-wilderness-walking-mountain-sky-tourze-lite.webp","height":612,"width":780,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"Landscape nature wilderness walking mountain sky","captionOriginal":"","width":{"Desktop":{"unit":"px"}},"height":{"Desktop":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"animation":{"type":{"Desktop":"fadeInUp"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"390"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px","point":"212"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"px","point":"0"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"positioningRight":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"positioningTop":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"positioningBottom":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"lazyLoad":true,"ariaLabel":"Landscape nature wilderness walking mountain sky","imageLoad":"lazy"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-TeQj7l animated guten-element-hide desktop-fadeInUp"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/landscape-nature-wilderness-walking-mountain-sky-tourze-lite.webp" height="612" width="780" alt="Landscape nature wilderness walking mountain sky" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-Olbufy","imgSrc":{"media":{"imageId":778,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sea-coast-water-architecture-sky-town-tourze-lite.webp","orientation":"landscape"},"medium":{"height":236,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sea-coast-water-architecture-sky-town-tourze-lite.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sea-coast-water-architecture-sky-town-tourze-lite.webp","height":508,"width":646,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"Sea coast water architecture sky town","captionOriginal":"","width":{"Desktop":{"unit":"px"}},"height":{"Desktop":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":150},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"323"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px","point":"174"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"positioningRight":{"Desktop":{"unit":"px","point":"0"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px","point":"0"}},"positioningTop":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px","point":"40"}},"positioningBottom":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"lazyLoad":true,"ariaLabel":"Sea coast water architecture sky town","imageLoad":"lazy"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-Olbufy animated guten-element-hide desktop-fadeInUp"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sea-coast-water-architecture-sky-town-tourze-lite.webp" height="508" width="646" alt="Sea coast water architecture sky town" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-f0XiBg","imgSrc":{"media":{"imageId":777,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/phang-nga-bay-phuket-james-bond-island-thailand-island-andaman-sea-tourze-lite.webp","orientation":"landscape"},"medium":{"height":295,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/phang-nga-bay-phuket-james-bond-island-thailand-island-andaman-sea-tourze-lite.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/phang-nga-bay-phuket-james-bond-island-thailand-island-andaman-sea-tourze-lite.webp","height":636,"width":646,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"Phang nga bay phuket james bond island thailand island","captionOriginal":"","width":{"Desktop":{"unit":"px"}},"height":{"Desktop":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":200},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"323"},"Mobile":{"unit":"px","point":"254"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"positioningRight":{"Desktop":{"unit":"px","point":""},"Mobile":{"unit":"px"}},"positioningTop":{"Desktop":{"unit":"px","point":""},"Mobile":{"unit":"px"}},"positioningBottom":{"Desktop":{"unit":"px","point":"0"},"Mobile":{"unit":"px"}},"lazyLoad":true,"ariaLabel":"Phang nga bay phuket james bond island thailand island","imageLoad":"lazy"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-f0XiBg animated guten-element-hide desktop-fadeInUp"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/phang-nga-bay-phuket-james-bond-island-thailand-island-andaman-sea-tourze-lite.webp" height="636" width="646" alt="Phang nga bay phuket james bond island thailand island" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":52,"Tablet":100},"elementId":"guten-fhopHA","verticalAlign":{"Desktop":"center"},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"60"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fhopHA"><div class="guten-column-wrapper" data-id="fhopHA"><!-- wp:gutenverse/heading {"elementId":"guten-XJsnIi","textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"52"},"Mobile":{"unit":"px","point":"46"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Tablet":"full"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-XJsnIi">Where Great Travel Experiences Begin</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-EsQlI6","gap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"80"}},"Mobile":{"unit":"px","dimension":{"bottom":"60"}}},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"px","point":"500"},"Tablet":{"unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-EsQlI6"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Your journey starts here. Explore destinations, find inspiration, and discover travel experiences crafted to make every moment unforgettable.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/fun-fact {"elementId":"guten-DurdNy","iconType":"none","prefix":"","safeNumber":"350","suffix":"","numberFormat":"point","title":"Travel Destinations","showSupper":true,"superColor":{"type":"variable","id":"gv-color-accent"},"superTypography":{"type":"variable","id":"gv-font-funfact-super","lineHeight":{"Mobile":{"unit":"em","point":"1"},"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"}},"size":{"Mobile":{"unit":"px","point":"46"},"Desktop":{"unit":"px","point":"50"},"Tablet":{"unit":"px"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"superTop":{"Desktop":"-1"},"superSpace":{"Desktop":"2"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"numberTypography":{"type":"variable","id":"gv-font-funfact-number","lineHeight":{"Mobile":{"unit":"px"},"Desktop":{"unit":"em","point":"1"}},"size":{"Mobile":{"unit":"px","point":"48"},"Desktop":{"unit":"px","point":"50"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"titleTypography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"numberBottomSpace":{"Desktop":"6"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"positioningType":{"Desktop":"inline"},"imageLoad":"eager"} -->
<div class="guten-element guten-DurdNy guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content block"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number-format="point" data-safe="350" data-number="" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Travel Destinations</span></div></div></div>
<!-- /wp:gutenverse/fun-fact -->

<!-- wp:gutenverse/fun-fact {"elementId":"guten-F9Jd4N","iconType":"none","prefix":"","safeNumber":"98","suffix":"","numberFormat":"point","title":"Satisfaction Rate","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"gv-color-accent"},"superTypography":{"type":"variable","id":"gv-font-funfact-number","lineHeight":{"Mobile":{"unit":"px"},"Desktop":{"unit":"em","point":"1"}},"size":{"Mobile":{"unit":"px","point":"48"},"Desktop":{"unit":"px","point":"50"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"superTop":{"Desktop":"-1"},"superSpace":{"Desktop":"2"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"numberTypography":{"type":"variable","id":"gv-font-funfact-number","lineHeight":{"Mobile":{"unit":"px"},"Desktop":{"unit":"em","point":"1"}},"size":{"Mobile":{"unit":"px","point":"48"},"Desktop":{"unit":"px","point":"50"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"titleTypography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"numberBottomSpace":{"Desktop":"6"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"20"}}},"positioningType":{"Desktop":"inline"},"imageLoad":"eager"} -->
<div class="guten-element guten-F9Jd4N guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content block"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number-format="point" data-safe="98" data-number="" data-duration="3500"></span><span class="suffix"></span><sup class="super">%</sup></div><span class="title">Satisfaction Rate</span></div></div></div>
<!-- /wp:gutenverse/fun-fact -->

<!-- wp:gutenverse/fun-fact {"elementId":"guten-kNwPTa","iconType":"none","prefix":"","safeNumber":"12","suffix":"K","numberFormat":"comma","title":"Happy Travelers","showSupper":true,"superColor":{"type":"variable","id":"gv-color-accent"},"superTypography":{"type":"variable","id":"gv-font-funfact-super","lineHeight":{"Mobile":{"unit":"em","point":"1"},"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"}},"size":{"Mobile":{"unit":"px","point":"46"},"Desktop":{"unit":"px","point":"50"},"Tablet":{"unit":"px"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"superTop":{"Desktop":"-1"},"superSpace":{"Desktop":"2"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"numberTypography":{"type":"variable","id":"gv-font-funfact-number","lineHeight":{"Mobile":{"unit":"px"},"Desktop":{"unit":"em","point":"1"}},"size":{"Mobile":{"unit":"px","point":"48"},"Desktop":{"unit":"px","point":"50"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"titleTypography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"numberBottomSpace":{"Desktop":"6"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"0"}}},"positioningType":{"Desktop":"inline"},"imageLoad":"eager"} -->
<div class="guten-element guten-kNwPTa guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content block"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number-format="comma" data-safe="12" data-number="" data-duration="3500"></span><span class="suffix">K</span><sup class="super">+</sup></div><span class="title">Happy Travelers</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
