<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tourze Lite Gutenverse Home Form Booking', 'tourze-lite' ),
	'categories' => array( 'tourze-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-Yob5RB","background":{"type":"video","image":{"Desktop":{"id":151,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/nature-mountain-hot-air-balloon-valley-travel-aircraft-1204991-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"slideImage":[],"videoLink":"https://youtu.be/iPYP_8roGhc?si=0XRFBFY2qur51vWQ","videoStartTime":"15","videoEndTime":"30","videoImage":{"Desktop":{"id":151,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/nature-mountain-hot-air-balloon-valley-travel-aircraft-1204991-pxhere.com_.webp"}}},"backgroundOverlay":{"type":"default","color":{"r":14,"g":14,"b":13,"a":0.35}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"right":"15","left":"15"}}},"zIndex":{"Desktop":1}} -->
<div class="section-wrapper" data-id="Yob5RB"><section class="wp-block-gutenverse-section guten-element guten-section guten-Yob5RB layout-boxed align-stretch"><div class="guten-video-background" data-property="{&quot;url&quot;:&quot;https://youtu.be/iPYP_8roGhc?si=0XRFBFY2qur51vWQ&quot;,&quot;class&quot;:&quot;guten-video-bg-wrapper&quot;,&quot;width&quot;:&quot;100%&quot;,&quot;height&quot;:&quot;100%&quot;,&quot;playing&quot;:true,&quot;muted&quot;:true,&quot;loop&quot;:true,&quot;playsinline&quot;:true,&quot;style&quot;:{&quot;zIndex&quot;:0,&quot;top&quot;:0,&quot;left&quot;:0,&quot;position&quot;:&quot;absolute&quot;,&quot;overflow&quot;:&quot;hidden&quot;,&quot;pointerEvents&quot;:&quot;none&quot;},&quot;config&quot;:{&quot;youtube&quot;:{&quot;playerVars&quot;:{&quot;showinfo&quot;:0,&quot;start&quot;:15,&quot;end&quot;:30}}}}"></div><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":42,"Tablet":70},"elementId":"guten-6ePFDc"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6ePFDc"><div class="guten-column-wrapper" data-id="6ePFDc"><!-- wp:gutenverse/wrapper {"elementId":"guten-ShkeOS","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}}},"animation":{"type":{"Desktop":"fadeInLeft"}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"40","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"30","bottom":"50","left":"30"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-ShkeOS animated guten-element-hide desktop-fadeInLeft"><div class="guten-inner-wrap" data-id="ShkeOS"><!-- wp:gutenverse/form-builder {"elementId":"guten-tJB735","formId":{"label":"Book Form","value":744},"successTypography":{"font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"400"},"successAlign":{"Desktop":"left"},"successPadding":{"Desktop":[],"Mobile":[]},"successBorder":{"radius":{"Desktop":[],"Mobile":[]}},"successBorderResponsive":{"Desktop":{"radius":[]},"Mobile":{"radius":[]}},"errorTypography":{"font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"400"},"errorAlign":{"Desktop":"left"},"errorPadding":{"Desktop":[],"Mobile":[]},"errorBorder":{"radius":{"Desktop":[]}},"errorBorderResponsive":{"Mobile":{"radius":[]}},"margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<form style="display:none" class="guten-element guten-form-builder guten-tJB735" data-form-id="744"><!-- wp:gutenverse/heading {"elementId":"guten-2v43Q1","textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"52"},"Mobile":{"unit":"px","point":"46"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-2v43Q1">Let’s Plan Your Perfect Trip</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-YecMX2","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"32"}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"501"}}} -->
<div class="guten-element gutenverse-text-editor guten-YecMX2"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Let us know what kind of trip you want</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-4lZG1F","inputLabel":"Destination","inputPlaceholder":"Where to go?","inputName":"input-text-destination","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"labelTypography":{"type":"variable","id":"gv-font-form-label","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"500"},"displayLogic":[],"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"4","top":"0"}},"Mobile":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"24","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"18"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"zIndex":{"Desktop":"0"},"inputPadding":{"Desktop":{"unit":"px","dimension":{"right":"14","left":"14","top":"12","bottom":"12"}},"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-border-input"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputAreaBoxShadow":{"color":{"r":16,"g":24,"b":40,"a":0.05},"blur":2,"vertical":1,"horizontal":0,"spread":0,"position":"outline"}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-4lZG1F hide-helper"><div class="label-wrapper"><label class="input-label">Destination</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Where to go?" name="input-text-destination" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-k4y0Hf","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"24","top":""}},"Mobile":{"unit":"px","dimension":{"bottom":"18"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="section-wrapper" data-id="k4y0Hf"><section class="wp-block-gutenverse-section guten-element guten-section guten-k4y0Hf layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-nONSTU","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"18","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nONSTU"><div class="guten-column-wrapper" data-id="nONSTU"><!-- wp:gutenverse/form-input-date {"elementId":"guten-ffVwm3","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"labelTypography":{"type":"variable","id":"gv-font-form-label","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"500"},"displayLogic":[],"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"4"}},"Mobile":[]},"helperPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"inputLabel":"Travel Date","inputPlaceholder":"Select date","inputName":"input-date-travel","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"14","bottom":"12","left":"14"}},"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-border-input"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputBgColorHover":{"Desktop":[]},"inputAreaBoxShadow":{"color":{"r":16,"g":24,"b":40,"a":0.05},"vertical":"1","blur":"2"}} -->
<div class="guten-element guten-form-input-date guten-form-input guten-input-position-top guten-ffVwm3 hide-helper"><div class="label-wrapper"><label class="input-label">Travel Date</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;date&quot;}" data-date="{&quot;dateFormat&quot;:&quot;F j, Y&quot;}" placeholder="Select date" name="input-date-travel" class="gutenverse-input gutenverse-input-date" type="text"/><div class="validation-error"></div></div></div>
<!-- /wp:gutenverse/form-input-date --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-3vw7u6","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"12","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3vw7u6"><div class="guten-column-wrapper" data-id="3vw7u6"><!-- wp:gutenverse/form-input-number {"elementId":"guten-s20iz6","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"labelTypography":{"type":"variable","id":"gv-font-form-label","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"500"},"displayLogic":[],"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"4"}},"Mobile":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"inputLabel":"Number of Travelers","inputPlaceholder":"ex : 2","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"14","bottom":"12","left":"14"}},"Mobile":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-border-input"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","color":{"type":"variable","id":"gv-color-accent"},"width":"1"}},"inputColorFocus":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputAreaBoxShadow":{"color":{"r":16,"g":24,"b":40,"a":0.05},"vertical":"1","blur":"2"}} -->
<div class="guten-element guten-form-input-number guten-form-input guten-input-position-top guten-s20iz6 hide-helper"><div class="label-wrapper"><label class="input-label">Number of Travelers</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;number&quot;,&quot;required&quot;:false,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="ex : 2" name="input-number" class="gutenverse-input gutenverse-input-number" type="number" min="0" max="100" step="1"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-number --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-email {"elementId":"guten-nAKDh9","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"labelTypography":{"type":"variable","id":"gv-font-form-label","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"500"},"displayLogic":[],"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"4","left":""}},"Mobile":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputLabel":"Your Email","inputPlaceholder":"you@mail.com","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"14","bottom":"12","left":"14"}},"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-border-input"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"inputAreaBoxShadow":{"color":{"r":16,"g":24,"b":40,"a":0.05},"vertical":1,"blur":2,"horizontal":0,"spread":0,"position":"outline"}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-nAKDh9 hide-helper"><div class="label-wrapper"><label class="input-label">Your Email</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="you@mail.com" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-VbEsn3","content":"Plan My Trip","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"showIcon":true,"iconType":"svg","icon":"gtn gtn-right-arrow-light","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"12"},"iconSize":{"Desktop":{"unit":"px","point":"20"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"32","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"26"}}},"padding":{"Desktop":[],"Mobile":[]},"color":{"type":"variable","id":"gv-color-white"},"iconColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"500"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"18","left":"18","top":"18","bottom":"18"}},"Mobile":[],"Tablet":[]},"condition":{"filter":[]}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-VbEsn3"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Plan My Trip</span><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M21.563 5.094q-0.344-0.344-0.813-0.344t-0.813 0.344q-0.344 0.313-0.344 0.781t0.344 0.813l8.188 8.188h-27q-0.469 0-0.797 0.328t-0.328 0.797 0.328 0.797 0.797 0.328h27l-8.188 8.188q-0.344 0.313-0.344 0.797t0.344 0.797q0.344 0.344 0.813 0.344t0.813-0.344l10.094-10.094q0.344-0.344 0.344-0.813t-0.344-0.813l-10.094-10.094z"></path>
</svg>
</div></button><div class="gutenverse-input-submit-loader"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M272 112C272 85.5 293.5 64 320 64C346.5 64 368 85.5 368 112C368 138.5 346.5 160 320 160C293.5 160 272 138.5 272 112zM272 528C272 501.5 293.5 480 320 480C346.5 480 368 501.5 368 528C368 554.5 346.5 576 320 576C293.5 576 272 554.5 272 528zM112 272C138.5 272 160 293.5 160 320C160 346.5 138.5 368 112 368C85.5 368 64 346.5 64 320C64 293.5 85.5 272 112 272zM480 320C480 293.5 501.5 272 528 272C554.5 272 576 293.5 576 320C576 346.5 554.5 368 528 368C501.5 368 480 346.5 480 320zM139 433.1C157.8 414.3 188.1 414.3 206.9 433.1C225.7 451.9 225.7 482.2 206.9 501C188.1 519.8 157.8 519.8 139 501C120.2 482.2 120.2 451.9 139 433.1zM139 139C157.8 120.2 188.1 120.2 206.9 139C225.7 157.8 225.7 188.1 206.9 206.9C188.1 225.7 157.8 225.7 139 206.9C120.2 188.1 120.2 157.8 139 139zM501 433.1C519.8 451.9 519.8 482.2 501 501C482.2 519.8 451.9 519.8 433.1 501C414.3 482.2 414.3 451.9 433.1 433.1C451.9 414.3 482.2 414.3 501 433.1z"></path></svg></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":58,"Tablet":30},"elementId":"guten-rGwygv","hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rGwygv hide-mobile"><div class="guten-column-wrapper" data-id="rGwygv"><!-- wp:gutenverse/spacer {"elementId":"guten-SjquaQ","space":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px","point":"100"},"Mobile":{"unit":"px","point":"10"}}} -->
<div class="guten-element guten-spacer guten-SjquaQ"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
