<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tourze Lite Gutenverse Home Feature Tour', 'tourze-lite' ),
	'categories' => array( 'tourze-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-q7HtPu","overflow":"hidden","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"80","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100"}}},"zIndex":{"Desktop":1}} -->
<div class="section-wrapper" data-id="q7HtPu"><section class="wp-block-gutenverse-section guten-element guten-section guten-q7HtPu layout-fullwidth align-stretch overflow-hidden"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-bdELdS","horizontalAlign":{"Desktop":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bdELdS"><div class="guten-column-wrapper" data-id="bdELdS"><!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-AA9cAh","padding":{"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"15","left":"15"}}}} -->
<div class="section-wrapper" data-id="AA9cAh"><section class="wp-block-gutenverse-section guten-element guten-section guten-AA9cAh layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-DZ0kBs"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DZ0kBs"><div class="guten-column-wrapper" data-id="DZ0kBs"><!-- wp:gutenverse/heading {"elementId":"guten-dxXXiD","textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"52"},"Mobile":{"unit":"px","point":"46"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-dxXXiD">Discover the Perfect<br>Tour for You</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-CDZt9a","verticalAlign":{"Desktop":"flex-end"},"horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-start"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-CDZt9a"><div class="guten-column-wrapper" data-id="CDZt9a"><!-- wp:gutenverse/text-editor {"elementId":"guten-iLP0eQ","gap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"containsAnchorTag":false,"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"501"}}} -->
<div class="guten-element gutenverse-text-editor guten-iLP0eQ"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Find a tour that matches your style. Whether you love relaxing beaches, cultural experiences, or adventurous journeys, we have the perfect trip waiting for you.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"2000"},"gap":"no","elementId":"guten-v1dEyT","margin":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":""}},"positioningLocation":"default","positioningLeft":{"Desktop":{"unit":"px"}},"positioningRight":{"Desktop":{"unit":"px"}},"positioningTop":{"Desktop":{"unit":"px"}},"positioningBottom":{"Desktop":{"unit":"px"}}} -->
<div class="section-wrapper" data-id="v1dEyT"><section class="wp-block-gutenverse-section guten-element guten-section guten-v1dEyT layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-ZsMpAq","margin":{"Tablet":{"unit":"px","dimension":{"right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"40"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":100}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ZsMpAq animated guten-element-hide desktop-fadeInRight"><div class="guten-column-wrapper" data-id="ZsMpAq"><!-- wp:gutenverse/wrapper {"elementId":"guten-qILI4i","displayType":"flex","displayWidth":{"Desktop":{"unit":"px","point":""}},"displayHeight":{"Desktop":{"unit":"px","point":""}},"horizontalAlign":{"Desktop":"space-between","Tablet":false,"Mobile":false},"verticalAlign":{"Desktop":"flex-end","Tablet":false,"Mobile":false},"background":{"type":"default","image":{"Desktop":{"id":159,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/landscape-nature-walking-person-mountain-hiking-1364947-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(39, 35, 26, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(39, 35, 26, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":100},"transform":{"transformOrigin":{"Desktop":""},"ease":"ease","delay":{"Desktop":null}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-qILI4i flex"><div class="guten-background-overlay"></div><div class="guten-inner-wrap" data-id="qILI4i"><!-- wp:gutenverse/spacer {"elementId":"guten-4rOBMG","space":{"Desktop":{"unit":"px","point":"300"},"Tablet":{"unit":"px","point":"240"},"Mobile":{"unit":"px"}},"animation":{"type":{"Desktop":"none"}}} -->
<div class="guten-element guten-spacer guten-4rOBMG"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/heading {"elementId":"guten-tnevo7","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"28"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-white"},"linkTypography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"28"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"170"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-tnevo7"><a href="#">Adventure Tours</a></h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/button {"elementId":"guten-sLS2Ac","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"buttonBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-white"}}},"buttonBorderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}},"showIcon":true,"icon":"gtn gtn-angle-right-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0xMi45NjkgNC4yODFsLTEuNDM4IDEuNDM4IDEwLjI4MSAxMC4yODEtMTAuMjgxIDEwLjI4MSAxLjQzOCAxLjQzOCAxMS0xMSAwLjY4OC0wLjcxOS0wLjY4OC0wLjcxOXoiPjwvcGF0aD4KPC9zdmc+Cg==","iconSpacing":{"Desktop":"0"},"iconSize":{"Desktop":{"unit":"px","point":"20"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"color":{"type":"variable","id":"gv-color-white"},"iconColor":{"type":"variable","id":"gv-color-white"},"positioningType":{"Desktop":"inline"},"ariaLabel":"Adventure tours detail page"} -->
<div class="guten-element guten-button-wrapper guten-sLS2Ac"><a class="guten-button guten-button-sm" href="#" aria-label="Adventure tours detail page"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M12.969 4.281l-1.438 1.438 10.281 10.281-10.281 10.281 1.438 1.438 11-11 0.688-0.719-0.688-0.719z"></path>
</svg>
</div><span></span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-yQ7FKv","padding":{"Desktop":{"unit":"px","dimension":{"right":"15","left":"15","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"40"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":0}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-yQ7FKv animated guten-element-hide desktop-fadeInRight"><div class="guten-column-wrapper" data-id="yQ7FKv"><!-- wp:gutenverse/wrapper {"elementId":"guten-Ii1LBW","displayType":"flex","displayWidth":{"Desktop":{"unit":"px","point":""}},"displayHeight":{"Desktop":{"unit":"px","point":""}},"horizontalAlign":{"Desktop":"space-between","Tablet":false,"Mobile":false},"verticalAlign":{"Desktop":"flex-end","Tablet":false,"Mobile":false},"background":{"type":"default","image":{"Desktop":{"id":158,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/beach-sea-sand-ocean-shore-vacation-833542-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(39, 35, 26, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(39, 35, 26, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"animation":{"type":{"Desktop":"none"},"delay":0,"duration":"normal"},"transform":{"transformOrigin":{"Desktop":""},"delay":{"Desktop":null},"ease":"ease"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-Ii1LBW flex"><div class="guten-background-overlay"></div><div class="guten-inner-wrap" data-id="Ii1LBW"><!-- wp:gutenverse/spacer {"elementId":"guten-JaplXM","space":{"Desktop":{"unit":"px","point":"300"},"Tablet":{"unit":"px","point":"240"}}} -->
<div class="guten-element guten-spacer guten-JaplXM"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/heading {"elementId":"guten-yyvXi0","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"28"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-white"},"linkTypography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"28"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"170"},"Mobile":{"unit":"px","point":"122"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-yyvXi0"><a href="#">Family Trips</a></h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/button {"elementId":"guten-DuZzYQ","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"buttonBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-white"}}},"buttonBorderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}},"showIcon":true,"icon":"gtn gtn-angle-right-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0xMi45NjkgNC4yODFsLTEuNDM4IDEuNDM4IDEwLjI4MSAxMC4yODEtMTAuMjgxIDEwLjI4MSAxLjQzOCAxLjQzOCAxMS0xMSAwLjY4OC0wLjcxOS0wLjY4OC0wLjcxOXoiPjwvcGF0aD4KPC9zdmc+Cg==","iconSpacing":{"Desktop":"0"},"iconSize":{"Desktop":{"unit":"px","point":"20"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"color":{"type":"variable","id":"gv-color-white"},"iconColor":{"type":"variable","id":"gv-color-white"},"positioningType":{"Desktop":"inline"},"ariaLabel":"Family trips detail page"} -->
<div class="guten-element guten-button-wrapper guten-DuZzYQ"><a class="guten-button guten-button-sm" href="#" aria-label="Family trips detail page"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M12.969 4.281l-1.438 1.438 10.281 10.281-10.281 10.281 1.438 1.438 11-11 0.688-0.719-0.688-0.719z"></path>
</svg>
</div><span></span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-Akohsu","padding":{"Desktop":{"unit":"px","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"40"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":0}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Akohsu animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="Akohsu"><!-- wp:gutenverse/wrapper {"elementId":"guten-KJPqyH","displayType":"flex","displayWidth":{"Desktop":{"unit":"px","point":""}},"displayHeight":{"Desktop":{"unit":"px","point":""}},"horizontalAlign":{"Desktop":"space-between","Tablet":false,"Mobile":false},"verticalAlign":{"Desktop":"flex-end","Tablet":false,"Mobile":false},"background":{"type":"default","image":{"Desktop":{"id":160,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/outdoor-person-people-woman-street-rain-1271249-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(39, 35, 26, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(39, 35, 26, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":0},"transform":{"transformOrigin":{"Desktop":"center center"},"ease":"ease","delay":{"Desktop":null}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-KJPqyH flex"><div class="guten-background-overlay"></div><div class="guten-inner-wrap" data-id="KJPqyH"><!-- wp:gutenverse/spacer {"elementId":"guten-hMFsjY","space":{"Desktop":{"unit":"px","point":"300"},"Tablet":{"unit":"px","point":"240"}}} -->
<div class="guten-element guten-spacer guten-hMFsjY"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/heading {"elementId":"guten-0RYgD3","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"28"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-white"},"linkTypography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"28"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"190"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-0RYgD3"><a href="#">Cultural Experiences</a></h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/button {"elementId":"guten-lAJyoo","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"buttonBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-white"}}},"buttonBorderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}},"showIcon":true,"icon":"gtn gtn-angle-right-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0xMi45NjkgNC4yODFsLTEuNDM4IDEuNDM4IDEwLjI4MSAxMC4yODEtMTAuMjgxIDEwLjI4MSAxLjQzOCAxLjQzOCAxMS0xMSAwLjY4OC0wLjcxOS0wLjY4OC0wLjcxOXoiPjwvcGF0aD4KPC9zdmc+Cg==","iconSpacing":{"Desktop":"0"},"iconSize":{"Desktop":{"unit":"px","point":"20"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"color":{"type":"variable","id":"gv-color-white"},"iconColor":{"type":"variable","id":"gv-color-white"},"positioningType":{"Desktop":"inline"},"ariaLabel":"Cultural experiences detail page"} -->
<div class="guten-element guten-button-wrapper guten-lAJyoo"><a class="guten-button guten-button-sm" href="#" aria-label="Cultural experiences detail page"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M12.969 4.281l-1.438 1.438 10.281 10.281-10.281 10.281 1.438 1.438 11-11 0.688-0.719-0.688-0.719z"></path>
</svg>
</div><span></span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-foz9rc","padding":{"Desktop":{"unit":"px","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"40"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":100}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-foz9rc animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="foz9rc"><!-- wp:gutenverse/wrapper {"elementId":"guten-nHlniy","displayType":"flex","displayWidth":{"Desktop":{"unit":"px","point":""}},"displayHeight":{"Desktop":{"unit":"px","point":""}},"horizontalAlign":{"Desktop":"space-between","Tablet":false,"Mobile":false},"verticalAlign":{"Desktop":"flex-end","Tablet":false,"Mobile":false},"background":{"type":"default","image":{"Desktop":{"id":163,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/photograph-sky-vacation-beauty-sea-honeymoon-1570885-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(39, 35, 26, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(39, 35, 26, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":100},"transform":{"transformOrigin":{"Desktop":"center center"},"delay":{"Desktop":null},"ease":"ease"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-nHlniy flex"><div class="guten-background-overlay"></div><div class="guten-inner-wrap" data-id="nHlniy"><!-- wp:gutenverse/spacer {"elementId":"guten-tEjn20","space":{"Desktop":{"unit":"px","point":"300"},"Tablet":{"unit":"px","point":"240"}}} -->
<div class="guten-element guten-spacer guten-tEjn20"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/heading {"elementId":"guten-omkdN9","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"28"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-white"},"linkTypography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"28"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"165"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-omkdN9"><a href="#">Island Holidays</a></h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/button {"elementId":"guten-TjxxJa","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"buttonBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-white"}}},"buttonBorderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-accent"}}},"showIcon":true,"icon":"gtn gtn-angle-right-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0xMi45NjkgNC4yODFsLTEuNDM4IDEuNDM4IDEwLjI4MSAxMC4yODEtMTAuMjgxIDEwLjI4MSAxLjQzOCAxLjQzOCAxMS0xMSAwLjY4OC0wLjcxOS0wLjY4OC0wLjcxOXoiPjwvcGF0aD4KPC9zdmc+Cg==","iconSpacing":{"Desktop":"0"},"iconSize":{"Desktop":{"unit":"px","point":"20"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"color":{"type":"variable","id":"gv-color-white"},"iconColor":{"type":"variable","id":"gv-color-white"},"positioningType":{"Desktop":"inline"},"ariaLabel":"Island holidays detail page"} -->
<div class="guten-element guten-button-wrapper guten-TjxxJa"><a class="guten-button guten-button-sm" href="#" aria-label="Island holidays detail page"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M12.969 4.281l-1.438 1.438 10.281 10.281-10.281 10.281 1.438 1.438 11-11 0.688-0.719-0.688-0.719z"></path>
</svg>
</div><span></span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/wrapper {"elementId":"guten-IuUk5Z","displayType":"flex","displayWidth":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"displayHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"horizontalAlign":{"Desktop":"center","Tablet":false,"Mobile":false},"verticalAlign":{"Desktop":"center","Tablet":false,"Mobile":false},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"15","left":"15"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-IuUk5Z flex"><div class="guten-inner-wrap" data-id="IuUk5Z"><!-- wp:gutenverse/text-editor {"elementId":"guten-jBVNpC","gap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"alignment":{"Desktop":null,"Mobile":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"containsAnchorTag":false,"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px","point":"501"}}} -->
<div class="guten-element gutenverse-text-editor guten-jBVNpC"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Discover more tours to find the experience that suits you best.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-sCf4aF","content":"Explore Tours","buttonWidth":{"Desktop":""},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":255,"g":117,"b":72,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"12"},"iconSize":{"Desktop":{"unit":"px","point":"20"}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"8"}}},"color":{"type":"variable","id":"gv-color-accent"},"iconColor":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"hoverIconColor":{"type":"variable","id":"gv-color-accent-hover"},"hoverTextColor":{"type":"variable","id":"gv-color-accent-hover"},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px","point":"549"}},"ariaLabel":"Explore more tours available"} -->
<div class="guten-element guten-button-wrapper guten-sCf4aF"><a class="guten-button guten-button-sm" href="#" aria-label="Explore more tours available"><span>Explore Tours</span><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M21.563 5.094q-0.344-0.344-0.813-0.344t-0.813 0.344q-0.344 0.313-0.344 0.781t0.344 0.813l8.188 8.188h-27q-0.469 0-0.797 0.328t-0.328 0.797 0.328 0.797 0.797 0.328h27l-8.188 8.188q-0.344 0.313-0.344 0.797t0.344 0.797q0.344 0.344 0.813 0.344t0.813-0.344l10.094-10.094q0.344-0.344 0.344-0.813t-0.344-0.813l-10.094-10.094z"></path>
</svg>
</div></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
