<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tourze Lite Gutenverse Footer', 'tourze-lite' ),
	'categories' => array( 'tourze-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-VXQKAM","background":{"type":"default","image":{"Desktop":{"id":219,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/landscape-balloon-hot-air-balloon-travel-aircraft-vehicle-719075-pxhere.com_.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"unit":"%","point":"77"}},"xposition":{"Desktop":{"unit":"px"}}},"backgroundOverlay":{"type":"gradient","color":{"r":49,"g":48,"b":43,"a":1},"gradientColor":[{"color":"rgba(49, 48, 43, 0.6)","active":true,"opacity":0.6,"id":1,"offset":"0.000"},{"color":"rgba(49, 48, 43, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"opacity":"1","padding":{"Desktop":{"unit":"px","dimension":{"top":"190","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="VXQKAM"><section class="wp-block-gutenverse-section guten-element guten-section guten-VXQKAM layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-iL6WcB","horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-iL6WcB"><div class="guten-column-wrapper" data-id="iL6WcB"><!-- wp:gutenverse/wrapper {"elementId":"guten-SLZk9h","displayType":"flex","displayWidth":{"Desktop":{"unit":"px"}},"displayHeight":{"Desktop":{"unit":"px"}},"horizontalAlign":{"Desktop":"center","Tablet":false,"Mobile":false}} -->
<div class="guten-element guten-wrap-helper no-margin guten-SLZk9h flex"><div class="guten-inner-wrap" data-id="SLZk9h"><!-- wp:gutenverse/heading {"elementId":"guten-oG2M2d","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-secondary"},"typography":{"type":"variable","id":"gv-font-heading-cta","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"58"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px","point":"48"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"586"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-oG2M2d">Let’s Make Your Dream Trip Happen</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/wrapper -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-su8Miv","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"32"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"418"}}} -->
<div class="guten-element gutenverse-text-editor guten-su8Miv"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Tell us what you’re looking for and we’ll help find the perfect tour.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-5SsLwu","content":"Get Free Consultation","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"28","left":"32"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"12"},"iconSize":{"Desktop":{"unit":"px","point":"20"}},"color":{"type":"variable","id":"gv-color-white"},"iconColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"500"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"549"}},"ariaLabel":"Contact our travel team"} -->
<div class="guten-element guten-button-wrapper guten-5SsLwu"><a class="guten-button guten-button-sm" href="#" aria-label="Contact our travel team"><span>Get Free Consultation</span><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M21.563 5.094q-0.344-0.344-0.813-0.344t-0.813 0.344q-0.344 0.313-0.344 0.781t0.344 0.813l8.188 8.188h-27q-0.469 0-0.797 0.328t-0.328 0.797 0.328 0.797 0.797 0.328h27l-8.188 8.188q-0.344 0.313-0.344 0.797t0.344 0.797q0.344 0.344 0.813 0.344t0.813-0.344l10.094-10.094q0.344-0.344 0.344-0.813t-0.344-0.813l-10.094-10.094z"></path>
</svg>
</div></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1290","Tablet":""},"gap":"no","elementId":"guten-GGvUjT","background":{"type":"default","color":{"type":"variable","id":"gv-color-background-secondary"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="GGvUjT"><section class="wp-block-gutenverse-section guten-element guten-section guten-GGvUjT layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-toROFW"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-toROFW"><div class="guten-column-wrapper" data-id="toROFW"><!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-TxQX5b","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"80"}}}} -->
<div class="section-wrapper" data-id="TxQX5b"><section class="wp-block-gutenverse-section guten-element guten-section guten-TxQX5b layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":42,"Tablet":100},"elementId":"guten-ncaM2U","padding":{"Tablet":{"unit":"px","dimension":{"bottom":"60"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ncaM2U"><div class="guten-column-wrapper" data-id="ncaM2U"><!-- wp:gutenverse/image {"elementId":"guten-cdiSmp","imgSrc":{"media":{"imageId":65,"sizes":{"thumbnail":{"height":60,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-tourze-white.webp","orientation":"landscape"},"medium":{"height":56,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-tourze-white.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-tourze-white.webp","height":60,"width":320,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"Tourze logo with white text","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"160"}},"height":{"Desktop":{"unit":"px"}},"url":"#","align":{"Desktop":"left"},"lazyLoad":true,"ariaLabel":"Tourze homepage","imageLoad":"lazy"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-cdiSmp"><a class="guten-image-wrapper" href="#" aria-label="Tourze homepage"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-tourze-white.webp" height="60" width="320" alt="Tourze logo with white text" loading="lazy"/></a></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":33.333},"elementId":"guten-QSe4gK","padding":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QSe4gK"><div class="guten-column-wrapper" data-id="QSe4gK"><!-- wp:gutenverse/heading {"elementId":"guten-FpGMNo","type":3,"textAlign":{"Desktop":null},"color":{"type":"variable","id":"gv-color-secondary"},"typography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"22"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-FpGMNo">Quick Link</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-mOVbWd","spaceBetween":{"Desktop":"12"},"alignList":{"Desktop":"flex-start"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textColorHover":{"type":"variable","id":"gv-color-white"},"textTypography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"}} -->
<div class="guten-element guten-icon-list guten-mOVbWd"><div class=" list-wrapper "><!-- wp:gutenverse/icon-list-item {"elementId":"guten-Sas7po","hasGlobalLink":true,"hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-Sas7po"><div class="list-divider"></div><a id="guten-Sas7po" href="#"><span class="list-text no-icon">Home</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-vTeCvM","hasGlobalLink":true,"hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-vTeCvM"><div class="list-divider"></div><a id="guten-vTeCvM" href="#"><span class="list-text no-icon">About Us</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-P8jMR3","hasGlobalLink":true,"hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-P8jMR3"><div class="list-divider"></div><a id="guten-P8jMR3" href="#"><span class="list-text no-icon">Tour Packages</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":33.333},"elementId":"guten-XPmlTD","padding":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-XPmlTD"><div class="guten-column-wrapper" data-id="XPmlTD"><!-- wp:gutenverse/heading {"elementId":"guten-71zd5y","type":3,"color":{"type":"variable","id":"gv-color-secondary"},"typography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"22"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-71zd5y">Term</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-xHIGMB","spaceBetween":{"Desktop":"12"},"alignList":{"Desktop":"flex-start"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textColorHover":{"type":"variable","id":"gv-color-white"},"textTypography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"}} -->
<div class="guten-element guten-icon-list guten-xHIGMB"><div class=" list-wrapper "><!-- wp:gutenverse/icon-list-item {"elementId":"guten-Io9bEP","hasGlobalLink":true,"hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-Io9bEP"><div class="list-divider"></div><a id="guten-Io9bEP" href="#"><span class="list-text no-icon">Privacy Policy</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-dCBHQ0","hasGlobalLink":true,"hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-dCBHQ0"><div class="list-divider"></div><a id="guten-dCBHQ0" href="#"><span class="list-text no-icon">Terms of Services</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-lqpc8l","hasGlobalLink":true,"hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-lqpc8l"><div class="list-divider"></div><a id="guten-lqpc8l" href="#"><span class="list-text no-icon">Cookies Settings</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":18,"Tablet":33.333},"elementId":"guten-w5oRnE"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-w5oRnE"><div class="guten-column-wrapper" data-id="w5oRnE"><!-- wp:gutenverse/heading {"elementId":"guten-YJx31B","type":3,"color":{"type":"variable","id":"gv-color-secondary"},"typography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"22"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"22"}},"font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-YJx31B">Contact</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-QsO7lu","spaceBetween":{"Desktop":"15"},"alignList":{"Desktop":"flex-start"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textColorHover":{"type":"variable","id":"gv-color-white"},"textTypography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"}} -->
<div class="guten-element guten-icon-list guten-QsO7lu"><div class=" list-wrapper "><!-- wp:gutenverse/icon-list-item {"elementId":"guten-ctl1KD","hasGlobalLink":true,"hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-ctl1KD"><div class="list-divider"></div><a id="guten-ctl1KD" href="#"><span class="list-text no-icon">1800 123 4567</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-rRFpfn","hasGlobalLink":true,"hideIcon":true} -->
<div class="guten-element guten-icon-list-item guten-rRFpfn"><div class="list-divider"></div><a id="guten-rRFpfn" href="#"><span class="list-text no-icon">example@example.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/divider {"elementId":"guten-aoEZbK","width":{"Desktop":"100"},"dividerColor":{"type":"variable","id":"gv-color-border"},"size":{"Desktop":"1"},"gap":{"Desktop":"0"}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-aoEZbK"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-Ntom26","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}}} -->
<div class="section-wrapper" data-id="Ntom26"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ntom26 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60},"elementId":"guten-4uS4Ur","verticalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-4uS4Ur"><div class="guten-column-wrapper" data-id="4uS4Ur"><!-- wp:gutenverse/text-editor {"elementId":"guten-AHgrgr","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"font":{"label":"Poppins","value":"Poppins","type":"google"},"weight":"400"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-text-secondary"},"linkTypography":{"lineHeight":{"Desktop":{"unit":"px"}},"size":{"Desktop":{"unit":"px"}},"weight":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"418"}}} -->
<div class="guten-element gutenverse-text-editor guten-AHgrgr"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Copyright © 2026. Powered by <a href="#">Tourze Lite</a> Tour &amp; Travel Agency Theme</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":40},"elementId":"guten-qTJCpa","verticalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-qTJCpa"><div class="guten-column-wrapper" data-id="qTJCpa"><!-- wp:gutenverse/social-icons {"elementId":"guten-2LlUdw","iconSize":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"gap":{"Desktop":"15"},"alignment":{"Desktop":"flex-end","Mobile":"flex-start"},"shape":"circle","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"r":255,"g":255,"b":255,"a":0.15},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"hoverIconColor":{"type":"variable","id":"gv-color-accent"}} -->
<div class="guten-element guten-social-icons guten-2LlUdw circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-6DSZEd","ariaLabel":"Follow us on Facebook","icon":"fab fa-facebook-f","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTgwIDI5OS4zVjUxMkgxOTZWMjk5LjNoODYuNWwxOC05Ny44SDE5NlYxNjYuOWMwLTUxLjcgMjAuMy03MS41IDcyLjctNzEuNWMxNi4zIDAgMjkuNCAuNCAzNyAxLjJWNy45QzI5MS40IDQgMjU2LjQgMCAyMzYuMiAwQzEyOS4zIDAgODAgNTAuNSA4MCAxNTkuNHY0Mi4xSDE0djk3LjhIODB6Ii8+PC9zdmc+","iconSize":{"Desktop":{"unit":"px"}}} -->
<div class="guten-element guten-social-icon guten-6DSZEd facebook svg"><a id="guten-6DSZEd" href="#" aria-label="Follow us on Facebook"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. --><path d="M80 299.3V512H196V299.3h86.5l18-97.8H196V166.9c0-51.7 20.3-71.5 72.7-71.5c16.3 0 29.4 .4 37 1.2V7.9C291.4 4 256.4 0 236.2 0C129.3 0 80 50.5 80 159.4v42.1H14v97.8H80z"/></svg></div></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-7Gj6Z9","ariaLabel":"Follow us on Instagram","icon":"fab fa-instagram","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTIyNC4xIDE0MWMtNjMuNiAwLTExNC45IDUxLjMtMTE0LjkgMTE0LjlzNTEuMyAxMTQuOSAxMTQuOSAxMTQuOVMzMzkgMzE5LjUgMzM5IDI1NS45IDI4Ny43IDE0MSAyMjQuMSAxNDF6bTAgMTg5LjZjLTQxLjEgMC03NC43LTMzLjUtNzQuNy03NC43czMzLjUtNzQuNyA3NC43LTc0LjcgNzQuNyAzMy41IDc0LjcgNzQuNy0zMy42IDc0LjctNzQuNyA3NC43em0xNDYuNC0xOTQuM2MwIDE0LjktMTIgMjYuOC0yNi44IDI2LjgtMTQuOSAwLTI2LjgtMTItMjYuOC0yNi44czEyLTI2LjggMjYuOC0yNi44IDI2LjggMTIgMjYuOCAyNi44em03Ni4xIDI3LjJjLTEuNy0zNS45LTkuOS02Ny43LTM2LjItOTMuOS0yNi4yLTI2LjItNTgtMzQuNC05My45LTM2LjItMzctMi4xLTE0Ny45LTIuMS0xODQuOSAwLTM1LjggMS43LTY3LjYgOS45LTkzLjkgMzYuMXMtMzQuNCA1OC0zNi4yIDkzLjljLTIuMSAzNy0yLjEgMTQ3LjkgMCAxODQuOSAxLjcgMzUuOSA5LjkgNjcuNyAzNi4yIDkzLjlzNTggMzQuNCA5My45IDM2LjJjMzcgMi4xIDE0Ny45IDIuMSAxODQuOSAwIDM1LjktMS43IDY3LjctOS45IDkzLjktMzYuMiAyNi4yLTI2LjIgMzQuNC01OCAzNi4yLTkzLjkgMi4xLTM3IDIuMS0xNDcuOCAwLTE4NC44ek0zOTguOCAzODhjLTcuOCAxOS42LTIyLjkgMzQuNy00Mi42IDQyLjYtMjkuNSAxMS43LTk5LjUgOS0xMzIuMSA5cy0xMDIuNyAyLjYtMTMyLjEtOWMtMTkuNi03LjgtMzQuNy0yMi45LTQyLjYtNDIuNi0xMS43LTI5LjUtOS05OS41LTktMTMyLjFzLTIuNi0xMDIuNyA5LTEzMi4xYzcuOC0xOS42IDIyLjktMzQuNyA0Mi42LTQyLjYgMjkuNS0xMS43IDk5LjUtOSAxMzIuMS05czEwMi43LTIuNiAxMzIuMSA5YzE5LjYgNy44IDM0LjcgMjIuOSA0Mi42IDQyLjYgMTEuNyAyOS41IDkgOTkuNSA5IDEzMi4xczIuNyAxMDIuNy05IDEzMi4xeiIvPjwvc3ZnPg==","iconSize":{"Desktop":{"unit":"px"}}} -->
<div class="guten-element guten-social-icon guten-7Gj6Z9 instagram svg"><a id="guten-7Gj6Z9" href="#" aria-label="Follow us on Instagram"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. --><path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/></svg></div></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-ZfSnHP","ariaLabel":"Follow us on Youtube","icon":"gtn gtn-youtube-v-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0zMS40MzggOC44NDRxLTAuMjgxLTEuMjgxLTEuMjM0LTIuMTQxdC0yLjIwMy0xLjAxNnEtMS41LTAuMTU2LTMtMC4yNXQtMy0wLjE0MS0zLTAuMDQ3aC02dC0zIDAuMDQ3LTMgMC4xNDEtMi45NjkgMC4yNXEtMS4yODEgMC4xNTYtMi4yMzQgMS4wMTZ0LTEuMjM0IDIuMTQxcS0wLjQwNiAxLjgxMy0wLjQ4NCAzLjc1dC0wLjA3OCAzLjgxMyAwLjA2MyAzLjgxMyAwLjUgMy43NXEwLjI4MSAxLjI4MSAxLjIzNCAyLjE0MXQyLjIzNCAwLjk4NHExLjQ2OSAwLjE4OCAyLjk2OSAwLjI4MXQzIDAuMTI1IDMgMC4wMzFxMS41IDAuMDMxIDMgMC4wMzF0My0wLjAzMXExLjUgMCAzLTAuMDMxdDMtMC4xMjUgMi45NjktMC4yODFxMS4yODEtMC4xMjUgMi4yMzQtMC45ODR0MS4yMzQtMi4xNDFxMC40MDYtMS44MTMgMC40ODQtMy43NXQwLjA3OC0zLjgxMy0wLjA2My0zLjgxMy0wLjUtMy43NXYwek0xMS44NzUgMjEuMzc1di0xMC41OTRxMS4yODEgMC42NTYgMi41MzEgMS4zNDQgMS4yODEgMC42NTYgMi41NDcgMS4zMTN0Mi41NDcgMS4zMTNxMS4yNSAwLjY4OCAyLjUzMSAxLjM0NC0xLjI1IDAuNjU2LTIuNTMxIDEuMzEzdC0yLjU0NyAxLjMxMy0yLjU0NyAxLjM0NHEtMS4yNSAwLjY1Ni0yLjUzMSAxLjMxM3YweiI+PC9wYXRoPgo8L3N2Zz4K","iconSize":{"Desktop":{"unit":"px"}}} -->
<div class="guten-element guten-social-icon guten-ZfSnHP youtube svg"><a id="guten-ZfSnHP" href="#" aria-label="Follow us on Youtube"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<path d="M31.438 8.844q-0.281-1.281-1.234-2.141t-2.203-1.016q-1.5-0.156-3-0.25t-3-0.141-3-0.047h-6t-3 0.047-3 0.141-2.969 0.25q-1.281 0.156-2.234 1.016t-1.234 2.141q-0.406 1.813-0.484 3.75t-0.078 3.813 0.063 3.813 0.5 3.75q0.281 1.281 1.234 2.141t2.234 0.984q1.469 0.188 2.969 0.281t3 0.125 3 0.031q1.5 0.031 3 0.031t3-0.031q1.5 0 3-0.031t3-0.125 2.969-0.281q1.281-0.125 2.234-0.984t1.234-2.141q0.406-1.813 0.484-3.75t0.078-3.813-0.063-3.813-0.5-3.75v0zM11.875 21.375v-10.594q1.281 0.656 2.531 1.344 1.281 0.656 2.547 1.313t2.547 1.313q1.25 0.688 2.531 1.344-1.25 0.656-2.531 1.313t-2.547 1.313-2.547 1.344q-1.25 0.656-2.531 1.313v0z"></path>
</svg>
</div></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-HTtIXX","ariaLabel":"Follow us on Tiktok","icon":"fab fa-tiktok","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQ0OCwyMDkuOTFhMjEwLjA2LDIxMC4wNiwwLDAsMS0xMjIuNzctMzkuMjVWMzQ5LjM4QTE2Mi41NSwxNjIuNTUsMCwxLDEsMTg1LDE4OC4zMVYyNzguMmE3NC42Miw3NC42MiwwLDEsMCw1Mi4yMyw3MS4xOFYwbDg4LDBhMTIxLjE4LDEyMS4xOCwwLDAsMCwxLjg2LDIyLjE3aDBBMTIyLjE4LDEyMi4xOCwwLDAsMCwzODEsMTAyLjM5YTEyMS40MywxMjEuNDMsMCwwLDAsNjcsMjAuMTRaIi8+PC9zdmc+","iconSize":{"Desktop":{"unit":"px"}}} -->
<div class="guten-element guten-social-icon guten-HTtIXX default svg"><a id="guten-HTtIXX" href="#" aria-label="Follow us on Tiktok"><div class="gutenverse-icon-svg"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. --><path d="M448,209.91a210.06,210.06,0,0,1-122.77-39.25V349.38A162.55,162.55,0,1,1,185,188.31V278.2a74.62,74.62,0,1,0,52.23,71.18V0l88,0a121.18,121.18,0,0,0,1.86,22.17h0A122.18,122.18,0,0,0,381,102.39a121.43,121.43,0,0,0,67,20.14Z"/></svg></div></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'is_sync' => true,
);
